In [ ]:
"""
Write a Python function called svd_2x2_singular_values(A) that finds an approximate singular value decomposition of a real 2 x 2 matrix using one Jacobi rotation. Input A: a NumPy array of shape (2, 2)

Rules You may use basic NumPy operations (matrix multiplication, transpose, element wise math, etc.). Do not call numpy.linalg.svd or any other high-level SVD routine. Stick to a single Jacobi step no iterative refinements.

Return A tuple (U, Σ, V_T) where U is a 2 x 2 orthogonal matrix, Σ is a length 2 NumPy array containing the singular values, and V_T is the transpose of the right-singular-vector matrix V.

Example:
Input:
a = [[2, 1], [1, 2]]
Output:
(array([[-0.70710678, -0.70710678],
                        [-0.70710678,  0.70710678]]),
        array([3., 1.]),
        array([[-0.70710678, -0.70710678],
               [-0.70710678,  0.70710678]]))
Reasoning:
U is the first matrix sigma is the second vector and V is the third matrix
"""

In [11]:
import numpy as np

def svd_2x2_singular_values(A: np.ndarray) -> tuple:
    S = A.T @ A
    s11, s12, s22 = S[0, 0], S[0, 1], S[1, 1]
    theta = 0.5 * np.arctan2(2 * s12, s11 - s22)

    c, s = np.cos(theta), np.sin(theta)
    V = np.array([[c, -s], [s, c]])

    D_diag = np.diag(V.T @ S @ V)
    Sigma = np.sqrt(np.maximum(0.0, D_diag))

    if Sigma[0] < Sigma[1]:
        Sigma = np.flip(Sigma)
        V = np.flip(V, axis=1)

    Sigma_inv = np.diag([1/x if x > 1e-9 else 0.0 for x in Sigma])
    U = A @ V @ Sigma_inv

    for i in range(2):
        n = np.linalg.norm(U[:, i])
        if n > 1e-9:
            U[:, i] /= n

    return (U, Sigma, V.T)

In [12]:
a = np.array([[2, 1], [1, 2]])
svd_2x2_singular_values(a)

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))